# Generated by Django 2.2.5 on 2019-11-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Aquí ingresa el nombre de la empresa', max_length=60)),
                ('email', models.EmailField(help_text='Aquí ingresa el email de la empresa', max_length=254)),
                ('telefono', models.CharField(help_text='Aquí ingresa el teléfono de la empresa', max_length=15)),
                ('servicios', models.TextField(help_text='Aquí ingresa los servicios de la empresa', max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
                ('red_social', models.CharField(help_text='Aquí ingresa la red social de la empresa', max_length=200)),
                ('direccion', models.CharField(help_text='Aquí ingresa la dirección de la empresa', max_length=200)),
                ('latitud', models.DecimalField(decimal_places=20, max_digits=50)),
                ('longitud', models.DecimalField(decimal_places=20, max_digits=50)),
            ],
        ),
    ]
