# Generated by Django 2.2.5 on 2019-12-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
            },
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Aquí ingresa el nombre de la empresa', max_length=70)),
                ('email', models.EmailField(help_text='Aquí ingresa el email de la empresa', max_length=254)),
                ('telefono', models.CharField(help_text='Aquí ingresa el teléfono de la empresa', max_length=30)),
                ('servicios', models.TextField(help_text='Aquí ingresa los servicios de la empresa', max_length=300)),
                ('imagen', models.ImageField(upload_to='')),
                ('red_social', models.CharField(help_text='Aquí ingresa la red social de la empresa', max_length=200)),
                ('cp', models.CharField(help_text='Código Postal', max_length=10)),
                ('municipio', models.CharField(help_text='Municipio', max_length=30)),
                ('colonia', models.CharField(help_text='Colonia', max_length=20)),
                ('calle', models.CharField(help_text='Calle', max_length=30)),
                ('noext', models.CharField(help_text='No. Exterior', max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Categoria')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Estados')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
    ]
