# Generated by Django 2.2.5 on 2019-12-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
