# Generated by Django 2.2.5 on 2019-12-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_empresas_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cp',
            field=models.CharField(help_text='Código Postal', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='noext',
            field=models.CharField(help_text='No. Exterior', max_length=30, verbose_name='No. Exterior'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(help_text='Aquí ingresa el nombre de la empresa', max_length=70, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(help_text='Aquí ingresa el teléfono de la empresa', max_length=30, verbose_name='Teléfono'),
        ),
    ]
