# Generated by Django 2.2.5 on 2020-01-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20191216_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.EmailField(blank=True, help_text='Aquí ingresa el email de la empresa', max_length=254),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='red_social',
            field=models.CharField(blank=True, help_text='Aquí ingresa la red social de la empresa', max_length=200),
        ),
    ]
