# Generated by Django 2.2.5 on 2020-01-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20200110_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='calle',
            field=models.TextField(help_text='Calle', max_length=200),
        ),
    ]
