# Generated by Django 2.2.5 on 2020-03-13 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_auto_20200112_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Aquí ingresa el nombre', max_length=70, verbose_name='Nombre')),
                ('telefono', models.CharField(help_text='Aquí ingresa el teléfono', max_length=30, verbose_name='Teléfono')),
                ('telefono2', models.CharField(help_text='Aquí ingresa el teléfono 2', max_length=30, verbose_name='Teléfono 2')),
                ('email', models.EmailField(blank=True, help_text='Aquí ingresa el email del participante', max_length=254)),
                ('imagen', models.ImageField(upload_to='')),
                ('red_social', models.CharField(blank=True, help_text='Aquí ingresa su red social', max_length=200)),
                ('municipio', models.CharField(help_text='Municipio', max_length=30)),
                ('colonia', models.CharField(help_text='Colonia', max_length=20)),
                ('created', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Estados')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
            },
        ),
    ]
