# Generated by Django 2.2.5 on 2020-03-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_participantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='num_votos',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
