# Generated by Django 2.2.5 on 2020-03-13 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20200312_1824'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='participantes',
    #         name='created',
    #     ),
    # ]
