# Generated by Django 2.2.5 on 2020-03-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_remove_participantes_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='colonia',
            field=models.CharField(blank=True, help_text='Colonia', max_length=20),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='municipio',
            field=models.CharField(blank=True, help_text='Municipio', max_length=30),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='nombre',
            field=models.CharField(blank=True, help_text='Aquí ingresa el nombre', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='num_votos',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='telefono',
            field=models.CharField(blank=True, help_text='Aquí ingresa el teléfono', max_length=30, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='telefono2',
            field=models.CharField(blank=True, help_text='Aquí ingresa el teléfono 2', max_length=30, unique=True, verbose_name='Teléfono 2'),
        ),
    ]
