# Generated by Django 2.2.5 on 2020-03-21 20:48

import apps.registro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20200317_1538'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='participantes',
            name='colonia',
            field=models.CharField(blank=True, help_text='Colonia', max_length=200),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='', validators=[apps.registro.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='telefono2',
            field=models.CharField(blank=True, help_text='Aquí ingresa el teléfono 2', max_length=30, verbose_name='Teléfono 2'),
        ),
    ]
